### ISSUE TITLE
Nginx restart

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#27]
After deploying, the website should be available both from the numeric IP url (like http://54.77.157.187) and the domain url (like http://staging.neurostars.org).
It works for the numeric IP but it doesn't for the domain. A `service nginx reload` from the webapp container is required.

I tried to add:

```
sleep 60
service nginx restart
```

at the end of [`run-webapp.sh.j2`](https://github.com/nimiq/ansible-biostar/blob/master/roles/docker_webapp/templates/run-webapp.sh.j2) but it didn't work.

I suggest to add to the end [`main.yml`](https://github.com/nimiq/ansible-biostar/blob/master/roles/docker_webapp/tasks/main.yml) the following:
- wait for http://54.77.157.187 to be up (this is to make sure that the webapp container is ready)
- if http://staging.neurostars.org is not up: `docker stop webapp; docker start webapp`

Checking a website can probably be done with the [uri module](http://docs.ansible.com/uri_module.html). Something like:

```
- name: Ensure the website is up and running
  uri:
    url: http://{{ ansible_ec2_public_ipv4 }}
    status_code: 200
    timeout: 300
    user: "{{ basic_auth_username }}"
    password: "{{ basic_auth_password }}"
    async: 300
    poll: 10
```
